### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by McKenjo** [The-Watcher-213/Castle-Summerfall#1]
After playing the game for about 5 minutes, I noticed quite a few spelling and grammar errors. A few examples:
cordanites should be coordinates,
werid should be weird, etc...
The spelling and grammar should probably be checked throughout the whole project.

**Comment by yomas000** [comment]
Ok thank you, that is helpful. We will resolve those issues and start spell checking from here on out. Thanks.
