### ISSUE TITLE
descend is spelled wrong

### ISSUE THREAD

**Issue by 9478881** [The-Watcher-213/Castle-Summerfall#7]
When it says put "descend" in to go to the next floor. It is confused. I looked at the code and found it was put as decend instead of descend. Also for some reason when i put the correct command "decend" in, below it, it says that I put the wrong input in after saying good game thanks for playing the demo.

**Comment by 9478881** [comment]
Its still saying Sorry I don't know what you wanted after you put in descend correctly and it says thanks for playing the demo.

**Comment by yomas000** [comment]
Yeah the demo is a known, but I will fix the descend error
